server:
  port: ${API_PORT:8080}
spring:
  application:
    name: openai
  ai:
    model:
      chat: ollama
    ollama:
      chat:
        model: qwen3:8b
      base-url: ${OLLAMA_HOST:http://localhost:11343}
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"