    SINOPSIS: {synopsis}
    PERSONAJES:
        {actors}
    PAGINAS PREVIAS:
        {pages}
    NUMERO PAGINA: {current} / {total}
PAGINA ACTUAL: {text} - {scene}
TARGET: {target}
HINT: {hint}

Evalua el hint del usuario para la página actual, genera una página o escena segun el target
SCENE -> solo la escena, TEXT -> solo el texto, BOTH -> ambos elementos
Sigue las reglas de edad y coherencia narrativa tanto de la sinopsis, personajes presentes con sus descripciones y roles como paginas previas.